from fastapi import APIRouter
from urllib.parse import quote
from datetime import datetime, timedelta

router = APIRouter(prefix="/calendar", tags=["Calendar"])


@router.get("/{user_id}")
def generate_calendar_link(user_id: int):

    # Example workout
    title = "ArogyaMitra Workout Session"
    description = (
        "Workout generated by ArogyaMitra AI.\n"
        "Today's workout:\n"
        "- Push-ups\n"
        "- Squats\n"
        "- Plank"
    )

    # Example date & time
    start = datetime.now() + timedelta(days=1)
    end = start + timedelta(hours=1)

    start_str = start.strftime("%Y%m%dT%H%M%S")
    end_str = end.strftime("%Y%m%dT%H%M%S")

    url = (
        "https://calendar.google.com/calendar/render?action=TEMPLATE"
        f"&text={quote(title)}"
        f"&dates={start_str}/{end_str}"
        f"&details={quote(description)}"
    )

    return {
        "calendar_url": url
    }